# Generated by Django 2.0.6 on 2019-10-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='user_profilepics')),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.IntegerField(default=users.models.gender)),
                ('address', models.CharField(max_length=50)),
                ('auth_level', models.IntegerField(default=1)),
                ('device_type', models.CharField(max_length=20)),
                ('device_token', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
