# Generated by Django 2.0.6 on 2019-08-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
