# Generated by Django 2.0.6 on 2019-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190817_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.FileField(default='', upload_to='category_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='image',
            field=models.FileField(default=0, upload_to='subcategory_images'),
            preserve_default=False,
        ),
    ]
